# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates twice a day
  schedule: [{ cron: "17 */12 * * *" }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: JasonCook599
          template: classic
          debug: true
          base: header, activity, community, repositories, metadata
          config_display: columns
          config_octicon: yes
          config_timezone: America/Toronto
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_from: 500
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          # plugin_pagespeed: yes
          # plugin_pagespeed_detailed: yes
          # plugin_pagespeed_url: .user.website
          # plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_stars: yes
          plugin_stars_limit: 4
          repositories_forks: yes
